name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up pip cache directory
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Cache virtualenv
        id: venv-cache
        uses: actions/cache@v4
        with:
          path: .oilvenv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-venv-

      - name: Create and install dependencies if cache miss
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .oilvenv
          .\.oilvenv\Scripts\python.exe -m pip install --upgrade pip
          .\.oilvenv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Confirm Python version
        run: .\.oilvenv\Scripts\python.exe --version

      - name: Style and Lint Validation (Black, isort, Flake8)
        run: |
          .\.oilvenv\Scripts\black . --exclude=.oilvenv --check --diff
          .\.oilvenv\Scripts\isort . --skip .oilvenv --check --diff
          .\.oilvenv\Scripts\python.exe -m flake8 . --exclude=.oilvenv --exit-zero

      - name: nbQA Notebook Quality Checks
        run: |
          if (Get-ChildItem -Recurse -Filter *.ipynb) {
            .\.oilvenv\Scripts\python.exe -m nbqa black . --line-length=88 --exclude .oilvenv
            .\.oilvenv\Scripts\python.exe -m nbqa isort . --skip .oilvenv
            .\.oilvenv\Scripts\python.exe -m nbqa flake8 . --exclude .oilvenv --exit-zero
          } else {
            echo "::notice::Skipping nbQA checks — no notebooks found in repo."
          }
            
      - name: Run pytest
        run: .\.oilvenv\Scripts\python.exe -m pytest tests --tb=short --maxfail=1 --disable-warnings -q || echo "::error::Tests failed"